/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahalh7876
 */
public class culminatingTest extends javax.swing.JFrame {

    /**
     * Creates new form culminatingTest
     */
    public culminatingTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        titleLbl = new javax.swing.JLabel();
        classLbl = new javax.swing.JLabel();
        avgClassLbl = new javax.swing.JLabel();
        wpnDmgLbl = new javax.swing.JLabel();
        wpnPriceLbl = new javax.swing.JLabel();
        wpnKawardLbl = new javax.swing.JLabel();
        clipSizeLbl = new javax.swing.JLabel();
        classLbl7 = new javax.swing.JLabel();
        classLbl8 = new javax.swing.JLabel();
        classLbl9 = new javax.swing.JLabel();
        classLbl10 = new javax.swing.JLabel();
        classLbl11 = new javax.swing.JLabel();
        classLbl12 = new javax.swing.JLabel();
        clipSizeLbl1 = new javax.swing.JLabel();
        classLbl14 = new javax.swing.JLabel();
        classLbl15 = new javax.swing.JLabel();
        classLbl16 = new javax.swing.JLabel();
        classLbl17 = new javax.swing.JLabel();
        classLbl18 = new javax.swing.JLabel();
        classLbl19 = new javax.swing.JLabel();
        classLbl20 = new javax.swing.JLabel();
        classLbl21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jComboBox1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Weapon 1" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Weapon 2" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(0, 51, 51));
        titleLbl.setText("CS:GO Weapon Master");

        classLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl.setForeground(new java.awt.Color(0, 51, 51));
        classLbl.setText("Class");

        avgClassLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        avgClassLbl.setForeground(new java.awt.Color(0, 51, 51));
        avgClassLbl.setText("Avg Class Damage");

        wpnDmgLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        wpnDmgLbl.setForeground(new java.awt.Color(0, 51, 51));
        wpnDmgLbl.setText("Weapon Damage");

        wpnPriceLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        wpnPriceLbl.setForeground(new java.awt.Color(0, 51, 51));
        wpnPriceLbl.setText("Weapon Price");

        wpnKawardLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        wpnKawardLbl.setForeground(new java.awt.Color(0, 51, 51));
        wpnKawardLbl.setText("Kill Award");

        clipSizeLbl.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        clipSizeLbl.setForeground(new java.awt.Color(0, 51, 51));
        clipSizeLbl.setText("Clip Size");

        classLbl7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl7.setForeground(new java.awt.Color(0, 51, 51));
        classLbl7.setText("0");

        classLbl8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl8.setForeground(new java.awt.Color(0, 51, 51));
        classLbl8.setText("0");

        classLbl9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl9.setForeground(new java.awt.Color(0, 51, 51));
        classLbl9.setText("0");

        classLbl10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl10.setForeground(new java.awt.Color(0, 51, 51));
        classLbl10.setText("0");

        classLbl11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl11.setForeground(new java.awt.Color(0, 51, 51));
        classLbl11.setText("0");

        classLbl12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl12.setForeground(new java.awt.Color(0, 51, 51));
        classLbl12.setText("0");

        clipSizeLbl1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        clipSizeLbl1.setForeground(new java.awt.Color(0, 51, 51));
        clipSizeLbl1.setText("Reserve Ammo");

        classLbl14.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl14.setForeground(new java.awt.Color(0, 51, 51));
        classLbl14.setText("0");

        classLbl15.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl15.setForeground(new java.awt.Color(0, 51, 51));
        classLbl15.setText("0");

        classLbl16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl16.setForeground(new java.awt.Color(0, 51, 51));
        classLbl16.setText("0");

        classLbl17.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl17.setForeground(new java.awt.Color(0, 51, 51));
        classLbl17.setText("0");

        classLbl18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl18.setForeground(new java.awt.Color(0, 51, 51));
        classLbl18.setText("0");

        classLbl19.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl19.setForeground(new java.awt.Color(0, 51, 51));
        classLbl19.setText("0");

        classLbl20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl20.setForeground(new java.awt.Color(0, 51, 51));
        classLbl20.setText("0");

        classLbl21.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        classLbl21.setForeground(new java.awt.Color(0, 51, 51));
        classLbl21.setText("0");

        jButton1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Compare guns");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classLbl12)
                    .addComponent(classLbl8)
                    .addComponent(classLbl7)
                    .addComponent(classLbl14)
                    .addComponent(classLbl10)
                    .addComponent(classLbl11)
                    .addComponent(classLbl9))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(classLbl)
                            .addComponent(wpnDmgLbl)
                            .addComponent(wpnPriceLbl)
                            .addComponent(wpnKawardLbl)
                            .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clipSizeLbl)
                            .addComponent(clipSizeLbl1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(avgClassLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(classLbl21)
                    .addComponent(classLbl17)
                    .addComponent(classLbl16)
                    .addComponent(classLbl15)
                    .addComponent(classLbl19)
                    .addComponent(classLbl20)
                    .addComponent(classLbl18))
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classLbl)
                            .addComponent(classLbl12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(avgClassLbl)
                            .addComponent(classLbl11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wpnDmgLbl)
                            .addComponent(classLbl10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wpnPriceLbl)
                            .addComponent(classLbl9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wpnKawardLbl)
                            .addComponent(classLbl8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(clipSizeLbl1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clipSizeLbl)
                                    .addComponent(classLbl7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classLbl14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(classLbl21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classLbl20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classLbl19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classLbl18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classLbl17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classLbl16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(classLbl15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(culminatingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(culminatingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(culminatingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(culminatingTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new culminatingTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgClassLbl;
    private javax.swing.JLabel classLbl;
    private javax.swing.JLabel classLbl10;
    private javax.swing.JLabel classLbl11;
    private javax.swing.JLabel classLbl12;
    private javax.swing.JLabel classLbl14;
    private javax.swing.JLabel classLbl15;
    private javax.swing.JLabel classLbl16;
    private javax.swing.JLabel classLbl17;
    private javax.swing.JLabel classLbl18;
    private javax.swing.JLabel classLbl19;
    private javax.swing.JLabel classLbl20;
    private javax.swing.JLabel classLbl21;
    private javax.swing.JLabel classLbl7;
    private javax.swing.JLabel classLbl8;
    private javax.swing.JLabel classLbl9;
    private javax.swing.JLabel clipSizeLbl;
    private javax.swing.JLabel clipSizeLbl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel wpnDmgLbl;
    private javax.swing.JLabel wpnKawardLbl;
    private javax.swing.JLabel wpnPriceLbl;
    // End of variables declaration//GEN-END:variables
}
